### PR TITLE
add network.allocate_ip option to allow for rootless CNI bridge utilisation

### PR DESCRIPTION
**Pull request by PauloMigAlmeida**
This PR is for a very specific scenario which has happened with me recently.

**My scenario:** I got access to server in which I do know (and will not possess) a privileged user and yet, I need set up the environment using singularity-composer. 

It turns out that the only step in which fakeroot (for obvious reasons) won't suffice is to attach the allocated IP to a running container because that requires real root access (or at least CAP_NET_*). 

So if we allow the user to run the services without allocating IPs then it can run without  needing a priviledge used...something like this (fictitious example) 

```
singularity run --bind ./env/postgres_env.sh:/.singularity.d/env/postgres_env.sh --bind ./postgres_data:/var/lib/postgresql/data --bind ./postgres_run:/var/run/postgresql  --fakeroot--net --network-args "portmap=5432:5432/tcp" --hostname cvatdb /home/paulo/workspace/cvat/singularity/cvatdb.sif
```

image

### CODE REVIEW

**Comment by PauloMigAlmeida** [comment]
Thanks @vsoch I will tweak the circleci config until I get it to work :)

**Comment by vsoch** [comment]
I think perhaps you forgot to save the circle config?

**Comment by vsoch** [comment]
I actually do that all the time - don't push control S hard enough and I forget to push one of my changes!

**Comment by PauloMigAlmeida** [comment]
It seems like the latest version I can point the org to is 3.7.3...any release beyond that has the asset file name changed from `singularity-<version>.tar.gz` to `singularity-ce-<version>tar.gz`

I will play with that more after lunch, thanks for the help vanessa

**Comment by vsoch** [comment]
okay I have a new orb to test - `singularity/singularity@dev:alpha` if you want to update and push once, I can keep re-running to test things out (I just updated the default singularity version so you can remove your changes there) and I suspect I'll need to debug the libseccomp issue.

**Comment by vsoch** [comment]
Thank you! I should be able to test it from here!

I do agree it's different/ separate from a singularity option. I think my question would be - is this something that you'd want to maintain with your singularity-compose.yaml (e.g., could the same recipe be run with and without this flag so it shouldn't be kept with the recipe itself?) If it's a consistent thing that is always needed, then I think it should be in the singularity-compose too. What about something like a network group? E.g.,

```yaml
version: "2.0"
instances:
  app:
    build:
      context: ./app
    network:
      allocate_ip: false # defaults to true
```

**Comment by PauloMigAlmeida** [comment]
On the code format subject, you may have come across with this one too.

When running `black --check scompose` but using the latest available version everything works out.

```
[paulo@localhost singularity-compose]$ black --check scompose
All done! ✨ 🍰 ✨
27 files would be left unchanged.
[paulo@localhost singularity-compose]$ pip uninstall black
Uninstalling black-21.9b0:
  Would remove:
    <redacted>
Proceed (y/n)? y
  Successfully uninstalled black-21.9b0
```

The error only happens when using the version <= `19.10b0`

```
[paulo@localhost singularity-compose]$ black --check scompose
would reformat /home/paulo/workspace/singularity-compose/scompose/client/__init__.py
Oh no! 💥 💔 💥
1 file would be reformatted, 26 files would be left unchanged.
```

I installed the version on that circle ci is installing via conda (so everything works out) but in case this happens in the future, you know why =)

**Comment by vsoch** [comment]
Ah thank you! Yes this has definitely happened to me before as well - black is a moving target!

**Comment by PauloMigAlmeida** [comment]
> I do agree it's different/ separate from a singularity option. I think my question would be - is this something that you'd want to maintain with your singularity-compose.yaml (e.g., could the same recipe be run with and without this flag so it shouldn't be kept with the recipe itself?) If it's a consistent thing that is always needed, then I think it should be in the singularity-compose too. What about something like a network group? E.g.,

You are right, this should be kept at the compose.yml file which would be applied at the instance level rather than globally. I will change my implementation.

**Comment by PauloMigAlmeida** [comment]
Thanks @vsoch! I changed the implementation to match the yaml structure that you suggested. Let me know if you have any comments on that

**Comment by vsoch** [comment]
okay posted an issue, hopefully will get some help! https://github.com/sylabs/singularity/issues/338

**Comment by vsoch** [comment]
It looks great! So we will just be waiting on the circle build - and I opened an issue on the Sylabs repo to ask for help about this error. If they don't have insight, I'll just try installing the correct version of libseccomp from source and call it a day. But hopefully they will have seen this error before.

The only remaining thing to do for approval on the PR is to add notes to the docs about this field group. I think the most straight forward thing would be to add a "Network Group" section after "Network" here: https://github.com/singularityhub/singularity-compose/blob/master/docs/spec/spec-2.0.md#networking that explains the very simple options we currently have.

**Comment by vsoch** [comment]
okay I can't figure it out - I'm going to have to refactor the entire CI this weekend to not use the orb, it's beyond me why I'm getting this older kernel and what looks to be an ABI issue. Sorry for the slowness, and thanks for letting me test on this PR!

**Review by vsoch — APPROVED** [review]
All is working! Docs look great, thanks for the changes.

**Comment by PauloMigAlmeida** [comment]
Super! 🎉  thanks a lot @vsoch

**Pull request merged**
